name: CI & SonarQube Analysis

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test 

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 


      - name: Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: BE requirements installation
        run: |
          python -m pip install --upgrade pip
          pip install -r back/app/requirements.txt
          pip install -r back/app/requirements-test.txt

      - name: BE test and coverage creation
        env:
          PYTHONPATH: .:back/app
        run: |
          export SNAPSHOT_STORAGE_ROOT=./snapshots
          pytest --cov=back/app --cov-report=xml:back/app/coverage.xml tests/

      - name: Node.js 18.x configure
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: FE requirements installation
        run: |
          cd front/apps/dashboard
          npm install
          cd ../../.. 

      - name: FE test coverage creation
        run: |
          cd front/apps/dashboard
          npm test -- --coverage
          cd ../../..

      - name: SonarQube 
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_key
            -Dsonar.sources=back/app,front/apps/dashboard/src
            -Dsonar.tests=back/app,front/apps/dashboard
            -Dsonar.verbose=true

            -Dsonar.python.coverage.reportPaths=back/app/coverage.xml
            
            -Dsonar.typescript.lcov.reportPaths=front/apps/dashboard/coverage/lcov.info
